-- PostgreSQL port of NADB schema (source: final_schema.sql, MySQL/InnoDB).
-- Run as superuser or owner:
--   createdb -E UTF8 nadb
--   psql -d nadb -f final_schema_postgres.sql
-- Note: PostgreSQL folds unquoted identifiers to lowercase.
-- Loaders must lowercase CIF keys (e.g. Cartn_x → cartn_x) before binding.

-- ============================================================
--  TIER 1 — ENTRY CORE
-- ============================================================

-- T1-01  entry  ── ABSOLUTE ROOT
CREATE TABLE IF NOT EXISTS entry (
    id  VARCHAR(20) NOT NULL,
    PRIMARY KEY (id)
);
COMMENT ON TABLE entry IS 'ROOT. One row per PDB entry. All other tables reference this.';


-- T1-02  pdbx_database_status  (1:1 with entry)
CREATE TABLE IF NOT EXISTS pdbx_database_status (
    entry_id                      VARCHAR(20) NOT NULL,
    status_code                   VARCHAR(10),
    recvd_initial_deposition_date DATE,
    deposit_site                  VARCHAR(20),
    process_site                  VARCHAR(20),
    status_code_sf                VARCHAR(10),
    pdb_format_compatible         VARCHAR(5),
    PRIMARY KEY (entry_id),
    CONSTRAINT fk_dbs_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);


-- T1-03  struct  (1:1 with entry)
CREATE TABLE IF NOT EXISTS struct (
    entry_id VARCHAR(20) NOT NULL,
    title    TEXT,
    PRIMARY KEY (entry_id),
    CONSTRAINT fk_struct_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);


-- T1-04  citation
CREATE TABLE IF NOT EXISTS citation (
    id                      VARCHAR(30) NOT NULL,
    entry_id                VARCHAR(20) NOT NULL,
    title                   TEXT,
    journal_abbrev          TEXT,
    journal_volume          VARCHAR(50),
    page_first              VARCHAR(20),
    page_last               VARCHAR(20),
    year                    SMALLINT,
    journal_id_ASTM         VARCHAR(20),
    country                 VARCHAR(10),
    journal_id_ISSN         VARCHAR(20),
    journal_id_CSD          VARCHAR(20),
    book_publisher          TEXT,
    pdbx_database_id_PubMed INT,
    pdbx_database_id_DOI    TEXT,
    PRIMARY KEY (id, entry_id),
    CONSTRAINT fk_cit_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_cit_entry ON citation (entry_id);


-- T1-05  citation_author
CREATE TABLE IF NOT EXISTS citation_author (
    id               INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    entry_id         VARCHAR(20) NOT NULL,
    citation_id      VARCHAR(30) NOT NULL,
    name             TEXT,
    ordinal          INT,
    identifier_ORCID TEXT,
    PRIMARY KEY (id),
    CONSTRAINT fk_ca_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE,
    CONSTRAINT fk_ca_citation
        FOREIGN KEY (citation_id, entry_id)
        REFERENCES citation(id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ca_entry    ON citation_author (entry_id);
CREATE INDEX IF NOT EXISTS idx_ca_citation ON citation_author (citation_id, entry_id);


-- ============================================================
--  TIER 2 — MOLECULES
-- ============================================================

-- T2-01  entity
CREATE TABLE IF NOT EXISTS entity (
    id                       VARCHAR(20) NOT NULL,
    entry_id                 VARCHAR(20) NOT NULL,
    type                     VARCHAR(50),
    pdbx_description         TEXT,
    formula_weight           REAL,
    pdbx_number_of_molecules INT,
    PRIMARY KEY (id, entry_id),
    CONSTRAINT fk_ent_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ent_entry ON entity (entry_id);


-- T2-02  entity_poly
CREATE TABLE IF NOT EXISTS entity_poly (
    entity_id                    VARCHAR(20) NOT NULL,
    entry_id                     VARCHAR(20) NOT NULL,
    type                         VARCHAR(100),
    pdbx_seq_one_letter_code_can TEXT,
    PRIMARY KEY (entity_id, entry_id),
    CONSTRAINT fk_epoly_entity
        FOREIGN KEY (entity_id, entry_id)
        REFERENCES entity(id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_epoly_entry ON entity_poly (entry_id);


-- T2-03  entity_poly_seq
CREATE TABLE IF NOT EXISTS entity_poly_seq (
    id        BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    entity_id VARCHAR(20) NOT NULL,
    entry_id  VARCHAR(20) NOT NULL,
    num       INT,
    mon_id    VARCHAR(10),
    hetero    VARCHAR(5),
    PRIMARY KEY (id),
    CONSTRAINT fk_eps_entity
        FOREIGN KEY (entity_id, entry_id)
        REFERENCES entity(id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_eps_entry  ON entity_poly_seq (entry_id);
CREATE INDEX IF NOT EXISTS idx_eps_entity ON entity_poly_seq (entity_id, entry_id);


-- T2-04  entity_src_gen
CREATE TABLE IF NOT EXISTS entity_src_gen (
    id                             INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    entity_id                      VARCHAR(20) NOT NULL,
    entry_id                       VARCHAR(20) NOT NULL,
    gene_src_common_name           TEXT,
    pdbx_gene_src_scientific_name  TEXT,
    pdbx_gene_src_ncbi_taxonomy_id INT,
    PRIMARY KEY (id),
    CONSTRAINT fk_esgen_entity
        FOREIGN KEY (entity_id, entry_id)
        REFERENCES entity(id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_esgen_entry  ON entity_src_gen (entry_id);
CREATE INDEX IF NOT EXISTS idx_esgen_entity ON entity_src_gen (entity_id, entry_id);


-- T2-05  pdbx_entity_nonpoly
CREATE TABLE IF NOT EXISTS pdbx_entity_nonpoly (
    entity_id VARCHAR(20) NOT NULL,
    entry_id  VARCHAR(20) NOT NULL,
    name      TEXT,
    comp_id   VARCHAR(10),
    PRIMARY KEY (entity_id, entry_id),
    CONSTRAINT fk_enp_entity
        FOREIGN KEY (entity_id, entry_id)
        REFERENCES entity(id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_enp_entry ON pdbx_entity_nonpoly (entry_id);


-- ============================================================
--  TIER 3 — CHAINS & SEQUENCE MAPPING
-- ============================================================

-- T3-01  struct_asym
CREATE TABLE IF NOT EXISTS struct_asym (
    id        VARCHAR(20) NOT NULL,
    entry_id  VARCHAR(20) NOT NULL,
    entity_id VARCHAR(20) NOT NULL,
    details   TEXT,
    PRIMARY KEY (id, entry_id),
    CONSTRAINT fk_asym_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE,
    CONSTRAINT fk_asym_entity
        FOREIGN KEY (entity_id, entry_id)
        REFERENCES entity(id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_asym_entry  ON struct_asym (entry_id);
CREATE INDEX IF NOT EXISTS idx_asym_entity ON struct_asym (entity_id, entry_id);


-- T3-02  pdbx_poly_seq_scheme
CREATE TABLE IF NOT EXISTS pdbx_poly_seq_scheme (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    asym_id       VARCHAR(20) NOT NULL,
    entry_id      VARCHAR(20) NOT NULL,
    entity_id     VARCHAR(20),
    seq_id        INT,
    mon_id        VARCHAR(10),
    ndb_seq_num   INT,
    pdb_seq_num   INT,
    auth_seq_num  VARCHAR(20),
    pdb_mon_id    VARCHAR(10),
    auth_mon_id   VARCHAR(10),
    pdb_strand_id VARCHAR(10),
    pdb_ins_code  VARCHAR(5),
    hetero        VARCHAR(5),
    PRIMARY KEY (id),
    CONSTRAINT fk_pss_asym
        FOREIGN KEY (asym_id, entry_id)
        REFERENCES struct_asym(id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_pss_entry ON pdbx_poly_seq_scheme (entry_id);
CREATE INDEX IF NOT EXISTS idx_pss_chain ON pdbx_poly_seq_scheme (asym_id, entry_id);


-- T3-03  struct_ref
CREATE TABLE IF NOT EXISTS struct_ref (
    id                VARCHAR(20) NOT NULL,
    entry_id          VARCHAR(20) NOT NULL,
    entity_id         VARCHAR(20) NOT NULL,
    db_name           VARCHAR(50),
    db_code           VARCHAR(100),
    pdbx_db_accession VARCHAR(100),
    PRIMARY KEY (id, entry_id),
    CONSTRAINT fk_sref_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE,
    CONSTRAINT fk_sref_entity
        FOREIGN KEY (entity_id, entry_id)
        REFERENCES entity(id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_sref_entry  ON struct_ref (entry_id);
CREATE INDEX IF NOT EXISTS idx_sref_entity ON struct_ref (entity_id, entry_id);


-- T3-04  struct_ref_seq
CREATE TABLE IF NOT EXISTS struct_ref_seq (
    align_id                    VARCHAR(20) NOT NULL,
    entry_id                    VARCHAR(20) NOT NULL,
    ref_id                      VARCHAR(20) NOT NULL,
    pdbx_PDB_id_code            VARCHAR(20),
    pdbx_strand_id              VARCHAR(10),
    seq_align_beg               INT,
    pdbx_seq_align_beg_ins_code VARCHAR(5),
    seq_align_end               INT,
    pdbx_seq_align_end_ins_code VARCHAR(5),
    pdbx_db_accession           VARCHAR(100),
    db_align_beg                INT,
    pdbx_db_align_beg_ins_code  VARCHAR(5),
    db_align_end                INT,
    pdbx_db_align_end_ins_code  VARCHAR(5),
    pdbx_auth_seq_align_beg     VARCHAR(20),
    pdbx_auth_seq_align_end     VARCHAR(20),
    PRIMARY KEY (align_id, entry_id),
    CONSTRAINT fk_srseq_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE,
    CONSTRAINT fk_srseq_ref
        FOREIGN KEY (ref_id, entry_id)
        REFERENCES struct_ref(id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_srseq_entry ON struct_ref_seq (entry_id);
CREATE INDEX IF NOT EXISTS idx_srseq_ref   ON struct_ref_seq (ref_id, entry_id);


-- ============================================================
--  TIER 4 — COORDINATE DATA
-- ============================================================

-- T4-01  atom_site (LARGEST TABLE)
CREATE TABLE IF NOT EXISTS atom_site (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    entry_id           VARCHAR(20) NOT NULL,
    group_PDB          VARCHAR(10),
    type_symbol        VARCHAR(5),
    label_atom_id      VARCHAR(20),
    label_alt_id       VARCHAR(5),
    label_comp_id      VARCHAR(10),
    label_asym_id      VARCHAR(20) NOT NULL,
    label_entity_id    VARCHAR(20),
    label_seq_id       INT,
    Cartn_x            REAL,
    Cartn_y            REAL,
    Cartn_z            REAL,
    occupancy          REAL,
    B_iso_or_equiv     REAL,
    auth_seq_id        VARCHAR(20),
    auth_asym_id       VARCHAR(10),
    auth_comp_id       VARCHAR(10),
    auth_atom_id       VARCHAR(20),
    pdbx_PDB_model_num INT,
    pdbx_formal_charge INT,
    pdbx_PDB_ins_code  VARCHAR(5),
    PRIMARY KEY (id),
    CONSTRAINT fk_as_asym
        FOREIGN KEY (label_asym_id, entry_id)
        REFERENCES struct_asym(id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_as_entry ON atom_site (entry_id);
CREATE INDEX IF NOT EXISTS idx_as_chain ON atom_site (label_asym_id, entry_id);
CREATE INDEX IF NOT EXISTS idx_as_model ON atom_site (entry_id, pdbx_PDB_model_num);
COMMENT ON TABLE atom_site IS 'All atom coordinates. LARGEST TABLE.';


-- T4-02  atom_sites (fractional-to-Cartesian, 1:1 with entry)
CREATE TABLE IF NOT EXISTS atom_sites (
    entry_id                VARCHAR(20) NOT NULL,
    fract_transf_matrix_1_1 DOUBLE PRECISION,
    fract_transf_matrix_1_2 DOUBLE PRECISION,
    fract_transf_matrix_1_3 DOUBLE PRECISION,
    fract_transf_matrix_2_1 DOUBLE PRECISION,
    fract_transf_matrix_2_2 DOUBLE PRECISION,
    fract_transf_matrix_2_3 DOUBLE PRECISION,
    fract_transf_matrix_3_1 DOUBLE PRECISION,
    fract_transf_matrix_3_2 DOUBLE PRECISION,
    fract_transf_matrix_3_3 DOUBLE PRECISION,
    fract_transf_vector_1   DOUBLE PRECISION,
    fract_transf_vector_2   DOUBLE PRECISION,
    fract_transf_vector_3   DOUBLE PRECISION,
    PRIMARY KEY (entry_id),
    CONSTRAINT fk_ats_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
COMMENT ON TABLE atom_sites IS 'Fractional-to-Cartesian matrix. 1:1. CIF []->_ in column names.';


-- T4-03  database_PDB_matrix (ORIGX transform, 1:1 with entry)
CREATE TABLE IF NOT EXISTS database_PDB_matrix (
    entry_id       VARCHAR(20) NOT NULL,
    origx_1_1      DOUBLE PRECISION,
    origx_1_2      DOUBLE PRECISION,
    origx_1_3      DOUBLE PRECISION,
    origx_2_1      DOUBLE PRECISION,
    origx_2_2      DOUBLE PRECISION,
    origx_2_3      DOUBLE PRECISION,
    origx_3_1      DOUBLE PRECISION,
    origx_3_2      DOUBLE PRECISION,
    origx_3_3      DOUBLE PRECISION,
    origx_vector_1 DOUBLE PRECISION,
    origx_vector_2 DOUBLE PRECISION,
    origx_vector_3 DOUBLE PRECISION,
    PRIMARY KEY (entry_id),
    CONSTRAINT fk_pdbmat_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
COMMENT ON TABLE database_PDB_matrix IS 'PDB ORIGX matrix. 1:1. CIF []->_ in column names.';


-- ============================================================
--  TIER 5 — SECONDARY STRUCTURE
-- ============================================================

-- T5-01  struct_conf_type (shared vocabulary, no entry_id)
CREATE TABLE IF NOT EXISTS struct_conf_type (
    id        VARCHAR(30) NOT NULL,
    criteria  TEXT,
    reference TEXT,
    PRIMARY KEY (id)
);
COMMENT ON TABLE struct_conf_type IS 'Helix/turn type lookup. Shared, no entry_id. Auto-seeded by loader.';


-- T5-02  struct_conf (soft-ref to struct_conf_type)
CREATE TABLE IF NOT EXISTS struct_conf (
    id                    VARCHAR(50) NOT NULL,
    entry_id              VARCHAR(20) NOT NULL,
    conf_type_id          VARCHAR(30),
    pdbx_PDB_helix_id     VARCHAR(10),
    beg_label_comp_id     VARCHAR(10),
    beg_label_asym_id     VARCHAR(20),
    beg_label_seq_id      INT,
    pdbx_beg_PDB_ins_code VARCHAR(5),
    end_label_comp_id     VARCHAR(10),
    end_label_asym_id     VARCHAR(20),
    end_label_seq_id      INT,
    pdbx_end_PDB_ins_code VARCHAR(5),
    beg_auth_comp_id      VARCHAR(10),
    beg_auth_asym_id      VARCHAR(10),
    beg_auth_seq_id       VARCHAR(20),
    end_auth_comp_id      VARCHAR(10),
    end_auth_asym_id      VARCHAR(10),
    end_auth_seq_id       VARCHAR(20),
    pdbx_PDB_helix_class  VARCHAR(5),
    details               TEXT,
    pdbx_PDB_helix_length INT,
    PRIMARY KEY (id, entry_id),
    CONSTRAINT fk_sconf_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_sconf_entry ON struct_conf (entry_id);
CREATE INDEX IF NOT EXISTS idx_sconf_type  ON struct_conf (conf_type_id);
COMMENT ON TABLE struct_conf IS 'Helices and turns. conf_type_id soft-ref struct_conf_type. Parent: entry.';


-- T5-03  struct_sheet
CREATE TABLE IF NOT EXISTS struct_sheet (
    id             VARCHAR(20) NOT NULL,
    entry_id       VARCHAR(20) NOT NULL,
    type           VARCHAR(50),
    number_strands INT,
    details        TEXT,
    PRIMARY KEY (id, entry_id),
    CONSTRAINT fk_ss_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ss_entry ON struct_sheet (entry_id);
COMMENT ON TABLE struct_sheet IS 'Beta-sheet parent. PK=(id,entry_id). Parent: entry.';


-- T5-04  struct_sheet_order  ("offset" is reserved in PG → quoted)
CREATE TABLE IF NOT EXISTS struct_sheet_order (
    id         INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    sheet_id   VARCHAR(20) NOT NULL,
    entry_id   VARCHAR(20) NOT NULL,
    range_id_1 VARCHAR(10),
    range_id_2 VARCHAR(10),
    "offset"   VARCHAR(20),
    sense      VARCHAR(20),
    PRIMARY KEY (id),
    CONSTRAINT fk_sso_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE,
    CONSTRAINT fk_sso_sheet
        FOREIGN KEY (sheet_id, entry_id)
        REFERENCES struct_sheet(id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_sso_entry ON struct_sheet_order (entry_id);
CREATE INDEX IF NOT EXISTS idx_sso_sheet ON struct_sheet_order (sheet_id, entry_id);
COMMENT ON TABLE struct_sheet_order IS 'Strand pair order + sense. Parent: struct_sheet(id,entry_id).';


-- T5-05  struct_sheet_range
CREATE TABLE IF NOT EXISTS struct_sheet_range (
    id                    VARCHAR(20) NOT NULL,
    sheet_id              VARCHAR(20) NOT NULL,
    entry_id              VARCHAR(20) NOT NULL,
    beg_label_comp_id     VARCHAR(10),
    beg_label_asym_id     VARCHAR(20),
    beg_label_seq_id      INT,
    pdbx_beg_PDB_ins_code VARCHAR(5),
    end_label_comp_id     VARCHAR(10),
    end_label_asym_id     VARCHAR(20),
    end_label_seq_id      INT,
    pdbx_end_PDB_ins_code VARCHAR(5),
    beg_auth_comp_id      VARCHAR(10),
    beg_auth_asym_id      VARCHAR(10),
    beg_auth_seq_id       VARCHAR(20),
    end_auth_comp_id      VARCHAR(10),
    end_auth_asym_id      VARCHAR(10),
    end_auth_seq_id       VARCHAR(20),
    PRIMARY KEY (id, sheet_id, entry_id),
    CONSTRAINT fk_ssr_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE,
    CONSTRAINT fk_ssr_sheet
        FOREIGN KEY (sheet_id, entry_id)
        REFERENCES struct_sheet(id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ssr_entry ON struct_sheet_range (entry_id);
CREATE INDEX IF NOT EXISTS idx_ssr_sheet ON struct_sheet_range (sheet_id, entry_id);
COMMENT ON TABLE struct_sheet_range IS 'Beta-strand residue ranges. Parent: struct_sheet(id,entry_id).';


-- T5-06  pdbx_struct_sheet_hbond
CREATE TABLE IF NOT EXISTS pdbx_struct_sheet_hbond (
    id                    INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    sheet_id              VARCHAR(20) NOT NULL,
    entry_id              VARCHAR(20) NOT NULL,
    range_id_1            VARCHAR(10),
    range_id_2            VARCHAR(10),
    range_1_label_atom_id VARCHAR(20),
    range_1_label_comp_id VARCHAR(10),
    range_1_label_asym_id VARCHAR(20),
    range_1_label_seq_id  INT,
    range_1_PDB_ins_code  VARCHAR(5),
    range_1_auth_atom_id  VARCHAR(20),
    range_1_auth_comp_id  VARCHAR(10),
    range_1_auth_asym_id  VARCHAR(10),
    range_1_auth_seq_id   VARCHAR(20),
    range_2_label_atom_id VARCHAR(20),
    range_2_label_comp_id VARCHAR(10),
    range_2_label_asym_id VARCHAR(20),
    range_2_label_seq_id  INT,
    range_2_PDB_ins_code  VARCHAR(5),
    range_2_auth_atom_id  VARCHAR(20),
    range_2_auth_comp_id  VARCHAR(10),
    range_2_auth_asym_id  VARCHAR(10),
    range_2_auth_seq_id   VARCHAR(20),
    PRIMARY KEY (id),
    CONSTRAINT fk_hb_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE,
    CONSTRAINT fk_hb_sheet
        FOREIGN KEY (sheet_id, entry_id)
        REFERENCES struct_sheet(id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_hb_entry ON pdbx_struct_sheet_hbond (entry_id);
CREATE INDEX IF NOT EXISTS idx_hb_sheet ON pdbx_struct_sheet_hbond (sheet_id, entry_id);
COMMENT ON TABLE pdbx_struct_sheet_hbond IS 'Sheet inter-strand H-bonds. Parent: struct_sheet(id,entry_id).';


-- ============================================================
--  TIER 6 — CRYSTALLOGRAPHY & REFINEMENT
-- ============================================================

-- T6-01  exptl (1:1 with entry)
CREATE TABLE IF NOT EXISTS exptl (
    entry_id        VARCHAR(20) NOT NULL,
    method          TEXT,
    crystals_number INT,
    PRIMARY KEY (entry_id),
    CONSTRAINT fk_exptl_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
COMMENT ON TABLE exptl IS 'Experimental method. 1:1. Parent: entry.';


-- T6-02  cell (1:1 with entry)
CREATE TABLE IF NOT EXISTS cell (
    entry_id    VARCHAR(20) NOT NULL,
    length_a    REAL,
    length_b    REAL,
    length_c    REAL,
    angle_alpha REAL,
    angle_beta  REAL,
    angle_gamma REAL,
    Z_PDB       INT,
    PRIMARY KEY (entry_id),
    CONSTRAINT fk_cell_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
COMMENT ON TABLE cell IS 'Unit cell dimensions. 1:1. Parent: entry.';


-- T6-03  symmetry (1:1 with entry)
-- CIF: _symmetry.space_group_name_H-M (hyphen) → SQL: space_group_name_H_M
CREATE TABLE IF NOT EXISTS symmetry (
    entry_id             VARCHAR(20) NOT NULL,
    space_group_name_H_M TEXT,
    Int_Tables_number    INT,
    PRIMARY KEY (entry_id),
    CONSTRAINT fk_sym_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
COMMENT ON TABLE symmetry IS 'Space group. CIF H-M (hyphen) stored as H_M (underscore). 1:1. Parent: entry.';


-- T6-04  reflns (1:1 with entry)
CREATE TABLE IF NOT EXISTS reflns (
    entry_id                   VARCHAR(20) NOT NULL,
    observed_criterion_sigma_I REAL,
    observed_criterion_sigma_F REAL,
    d_resolution_low           REAL,
    d_resolution_high          REAL,
    number_obs                 INT,
    number_all                 INT,
    percent_possible_obs       REAL,
    PRIMARY KEY (entry_id),
    CONSTRAINT fk_reflns_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
COMMENT ON TABLE reflns IS 'Reflection statistics. 1:1. Parent: entry.';


-- T6-05  diffrn
CREATE TABLE IF NOT EXISTS diffrn (
    id           VARCHAR(20) NOT NULL,
    entry_id     VARCHAR(20) NOT NULL,
    ambient_temp REAL,
    PRIMARY KEY (id, entry_id),
    CONSTRAINT fk_diffrn_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_diffrn_entry ON diffrn (entry_id);
COMMENT ON TABLE diffrn IS 'Diffraction experiment(s). PK=(id,entry_id). 1:N. Parent: entry.';


-- T6-06  refine (1:1 with entry)
CREATE TABLE IF NOT EXISTS refine (
    entry_id                           VARCHAR(20) NOT NULL,
    pdbx_refine_id                     TEXT,
    ls_number_reflns_obs               INT,
    ls_number_reflns_all               INT,
    pdbx_ls_sigma_I                    REAL,
    pdbx_ls_sigma_F                    REAL,
    ls_d_res_low                       REAL,
    ls_d_res_high                      REAL,
    ls_percent_reflns_obs              REAL,
    ls_R_factor_obs                    REAL,
    ls_R_factor_all                    REAL,
    ls_R_factor_R_work                 REAL,
    ls_R_factor_R_free                 REAL,
    ls_percent_reflns_R_free           REAL,
    ls_number_reflns_R_free            INT,
    solvent_model_details              TEXT,
    pdbx_solvent_vdw_probe_radii       REAL,
    pdbx_solvent_shrinkage_radii       REAL,
    pdbx_starting_model                TEXT,
    pdbx_method_to_determine_struct    TEXT,
    pdbx_stereochemistry_target_values TEXT,
    pdbx_R_Free_selection_details      TEXT,
    overall_SU_ML                      REAL,
    pdbx_overall_phase_error           REAL,
    pdbx_diffrn_id                     VARCHAR(20),
    PRIMARY KEY (entry_id),
    CONSTRAINT fk_refine_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
COMMENT ON TABLE refine IS 'Refinement statistics. 1:1. Parent: entry.';


-- ============================================================
--  TIER 7 — CHEMISTRY
-- ============================================================

-- T7-01  chem_comp (shared, no entry_id)
CREATE TABLE IF NOT EXISTS chem_comp (
    id             VARCHAR(10) NOT NULL,
    type           VARCHAR(100),
    mon_nstd_flag  VARCHAR(5),
    name           TEXT,
    pdbx_synonyms  TEXT,
    formula        TEXT,
    formula_weight REAL,
    PRIMARY KEY (id)
);
COMMENT ON TABLE chem_comp IS 'Chemical component dictionary. Shared, no entry_id. ON CONFLICT DO NOTHING on insert.';


-- ============================================================
--  TIER 8 — NtC RNA ANNOTATIONS
-- ============================================================

-- T8-01  ndb_struct_ntc_overall (1:1 with entry)
CREATE TABLE IF NOT EXISTS ndb_struct_ntc_overall (
    entry_id                    VARCHAR(20) NOT NULL,
    confal_score                REAL,
    confal_percentile           INT,
    ntc_version                 VARCHAR(20),
    cana_version                VARCHAR(20),
    num_steps                   INT,
    num_classified              INT,
    num_unclassified            INT,
    num_unclassified_rmsd_close INT,
    PRIMARY KEY (entry_id),
    CONSTRAINT fk_ntco_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
COMMENT ON TABLE ndb_struct_ntc_overall IS 'NtC overall stats. 1:1. CIF single-value form. Parent: entry.';


-- T8-02  ndb_struct_ntc_step
CREATE TABLE IF NOT EXISTS ndb_struct_ntc_step (
    id                INT         NOT NULL,
    entry_id          VARCHAR(20) NOT NULL,
    name              TEXT,
    PDB_model_number  INT,
    label_entity_id_1 VARCHAR(20),
    label_asym_id_1   VARCHAR(20),
    label_seq_id_1    INT,
    label_comp_id_1   VARCHAR(10),
    label_alt_id_1    VARCHAR(5),
    label_entity_id_2 VARCHAR(20),
    label_asym_id_2   VARCHAR(20),
    label_seq_id_2    INT,
    label_comp_id_2   VARCHAR(10),
    label_alt_id_2    VARCHAR(5),
    auth_asym_id_1    VARCHAR(10),
    auth_seq_id_1     VARCHAR(20),
    auth_asym_id_2    VARCHAR(10),
    auth_seq_id_2     VARCHAR(20),
    PDB_ins_code_1    VARCHAR(5),
    PDB_ins_code_2    VARCHAR(5),
    PRIMARY KEY (id, entry_id),
    CONSTRAINT fk_ntcs_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ntcs_entry ON ndb_struct_ntc_step (entry_id);
COMMENT ON TABLE ndb_struct_ntc_step IS 'Dinucleotide steps. PK=(id,entry_id). PARENT of 3 NtC children. entry_id injected by loader.';


-- T8-03  ndb_struct_ntc_step_summary (1:1 with ndb_struct_ntc_step)
CREATE TABLE IF NOT EXISTS ndb_struct_ntc_step_summary (
    step_id                                   INT         NOT NULL,
    entry_id                                  VARCHAR(20) NOT NULL,
    assigned_CANA                             VARCHAR(10),
    assigned_NtC                              VARCHAR(10),
    confal_score                              REAL,
    euclidean_distance_NtC_ideal              REAL,
    cartesian_rmsd_closest_NtC_representative REAL,
    closest_CANA                              VARCHAR(10),
    closest_NtC                               VARCHAR(10),
    closest_step_golden                       TEXT,
    PRIMARY KEY (step_id, entry_id),
    CONSTRAINT fk_ntcss_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE,
    CONSTRAINT fk_ntcss_step
        FOREIGN KEY (step_id, entry_id)
        REFERENCES ndb_struct_ntc_step(id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ntcss_entry ON ndb_struct_ntc_step_summary (entry_id);
COMMENT ON TABLE ndb_struct_ntc_step_summary IS 'NtC assignment + CONFAL per step. entry_id injected by loader.';


-- T8-04  ndb_struct_ntc_step_parameters (1:1 with ndb_struct_ntc_step)
CREATE TABLE IF NOT EXISTS ndb_struct_ntc_step_parameters (
    step_id              INT         NOT NULL,
    entry_id             VARCHAR(20) NOT NULL,
    tor_delta_1          REAL,
    tor_epsilon_1        REAL,
    tor_zeta_1           REAL,
    tor_alpha_2          REAL,
    tor_beta_2           REAL,
    tor_gamma_2          REAL,
    tor_delta_2          REAL,
    tor_chi_1            REAL,
    tor_chi_2            REAL,
    dist_NN              REAL,
    dist_CC              REAL,
    tor_NCCN             REAL,
    diff_tor_delta_1     REAL,
    diff_tor_epsilon_1   REAL,
    diff_tor_zeta_1      REAL,
    diff_tor_alpha_2     REAL,
    diff_tor_beta_2      REAL,
    diff_tor_gamma_2     REAL,
    diff_tor_delta_2     REAL,
    diff_tor_chi_1       REAL,
    diff_tor_chi_2       REAL,
    diff_dist_NN         REAL,
    diff_dist_CC         REAL,
    diff_tor_NCCN        REAL,
    confal_tor_delta_1   REAL,
    confal_tor_epsilon_1 REAL,
    confal_tor_zeta_1    REAL,
    confal_tor_alpha_2   REAL,
    confal_tor_beta_2    REAL,
    confal_tor_gamma_2   REAL,
    confal_tor_delta_2   REAL,
    confal_tor_chi_1     REAL,
    confal_tor_chi_2     REAL,
    confal_dist_NN       REAL,
    confal_dist_CC       REAL,
    confal_tor_NCCN      REAL,
    details              TEXT,
    PRIMARY KEY (step_id, entry_id),
    CONSTRAINT fk_ntcsp_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE,
    CONSTRAINT fk_ntcsp_step
        FOREIGN KEY (step_id, entry_id)
        REFERENCES ndb_struct_ntc_step(id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ntcsp_entry ON ndb_struct_ntc_step_parameters (entry_id);
COMMENT ON TABLE ndb_struct_ntc_step_parameters IS 'Torsion suite per step (37 floats). entry_id injected by loader.';


-- T8-05  ndb_struct_sugar_step_parameters (1:1 with ndb_struct_ntc_step)
CREATE TABLE IF NOT EXISTS ndb_struct_sugar_step_parameters (
    step_id     INT         NOT NULL,
    entry_id    VARCHAR(20) NOT NULL,
    P_1         REAL,
    tau_1       REAL,
    Pn_1        VARCHAR(10),
    P_2         REAL,
    tau_2       REAL,
    Pn_2        VARCHAR(10),
    nu_1_1      REAL,
    nu_1_2      REAL,
    nu_1_3      REAL,
    nu_1_4      REAL,
    nu_1_5      REAL,
    nu_2_1      REAL,
    nu_2_2      REAL,
    nu_2_3      REAL,
    nu_2_4      REAL,
    nu_2_5      REAL,
    diff_nu_1_1 REAL,
    diff_nu_1_2 REAL,
    diff_nu_1_3 REAL,
    diff_nu_1_4 REAL,
    diff_nu_1_5 REAL,
    diff_nu_2_1 REAL,
    diff_nu_2_2 REAL,
    diff_nu_2_3 REAL,
    diff_nu_2_4 REAL,
    diff_nu_2_5 REAL,
    PRIMARY KEY (step_id, entry_id),
    CONSTRAINT fk_sugar_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE,
    CONSTRAINT fk_sugar_step
        FOREIGN KEY (step_id, entry_id)
        REFERENCES ndb_struct_ntc_step(id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_sugar_entry ON ndb_struct_sugar_step_parameters (entry_id);
COMMENT ON TABLE ndb_struct_sugar_step_parameters IS 'Ribose pucker + nu angles per step. entry_id injected by loader.';


-- T8-06  ndb_base_pair_list
CREATE TABLE IF NOT EXISTS ndb_base_pair_list (
    base_pair_id     INT         NOT NULL,
    entry_id         VARCHAR(20) NOT NULL,
    PDB_model_number INT,
    asym_id_1        VARCHAR(20),
    entity_id_1      VARCHAR(20),
    seq_id_1         INT,
    comp_id_1        VARCHAR(10),
    PDB_ins_code_1   VARCHAR(5),
    alt_id_1         VARCHAR(5),
    struct_oper_id_1 VARCHAR(20),
    asym_id_2        VARCHAR(20),
    entity_id_2      VARCHAR(20),
    seq_id_2         INT,
    comp_id_2        VARCHAR(10),
    PDB_ins_code_2   VARCHAR(5),
    alt_id_2         VARCHAR(5),
    struct_oper_id_2 VARCHAR(20),
    auth_asym_id_1   VARCHAR(10),
    auth_seq_id_1    VARCHAR(20),
    auth_asym_id_2   VARCHAR(10),
    auth_seq_id_2    VARCHAR(20),
    PRIMARY KEY (base_pair_id, entry_id),
    CONSTRAINT fk_bpl_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_bpl_entry ON ndb_base_pair_list (entry_id);
COMMENT ON TABLE ndb_base_pair_list IS 'Base pair list (WC + non-canonical). entry_id injected by loader.';


-- T8-07  ndb_base_pair_annotation
-- CIF: l-w_family_num, l-w_family (hyphen) → SQL: lw_family_num, lw_family
CREATE TABLE IF NOT EXISTS ndb_base_pair_annotation (
    id            INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    base_pair_id  INT         NOT NULL,
    entry_id      VARCHAR(20) NOT NULL,
    orientation   VARCHAR(20),
    base_1_edge   TEXT,
    base_2_edge   TEXT,
    lw_family_num INT,
    lw_family     VARCHAR(10),
    class         VARCHAR(30),
    subclass      VARCHAR(50),
    PRIMARY KEY (id),
    CONSTRAINT fk_bpa_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE,
    CONSTRAINT fk_bpa_pair
        FOREIGN KEY (base_pair_id, entry_id)
        REFERENCES ndb_base_pair_list(base_pair_id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_bpa_entry ON ndb_base_pair_annotation (entry_id);
CREATE INDEX IF NOT EXISTS idx_bpa_pair  ON ndb_base_pair_annotation (base_pair_id, entry_id);
COMMENT ON TABLE ndb_base_pair_annotation IS 'LW annotation (cWW, cWH...). CIF l-w_family->lw_family. entry_id injected by loader.';


-- ============================================================
--  TIER 9 — VALIDATION
-- ============================================================

-- T9-01  pdbx_validate_rmsd_bond
CREATE TABLE IF NOT EXISTS pdbx_validate_rmsd_bond (
    id                      INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    entry_id                VARCHAR(20) NOT NULL,
    PDB_model_num           INT,
    auth_atom_id_1          VARCHAR(20),
    auth_asym_id_1          VARCHAR(10),
    auth_comp_id_1          VARCHAR(10),
    auth_seq_id_1           VARCHAR(20),
    PDB_ins_code_1          VARCHAR(5),
    label_alt_id_1          VARCHAR(5),
    auth_atom_id_2          VARCHAR(20),
    auth_asym_id_2          VARCHAR(10),
    auth_comp_id_2          VARCHAR(10),
    auth_seq_id_2           VARCHAR(20),
    PDB_ins_code_2          VARCHAR(5),
    label_alt_id_2          VARCHAR(5),
    bond_value              REAL,
    bond_target_value       REAL,
    bond_deviation          REAL,
    bond_standard_deviation REAL,
    linker_flag             VARCHAR(5),
    PRIMARY KEY (id),
    CONSTRAINT fk_vrb_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_vrb_entry ON pdbx_validate_rmsd_bond (entry_id);
COMMENT ON TABLE pdbx_validate_rmsd_bond IS 'Bond RMSD outliers. entry_id injected by loader. CIF id ignored (IDENTITY).';


-- T9-02  pdbx_validate_rmsd_angle
CREATE TABLE IF NOT EXISTS pdbx_validate_rmsd_angle (
    id                       INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    entry_id                 VARCHAR(20) NOT NULL,
    PDB_model_num            INT,
    auth_atom_id_1           VARCHAR(20),
    auth_asym_id_1           VARCHAR(10),
    auth_comp_id_1           VARCHAR(10),
    auth_seq_id_1            VARCHAR(20),
    PDB_ins_code_1           VARCHAR(5),
    label_alt_id_1           VARCHAR(5),
    auth_atom_id_2           VARCHAR(20),
    auth_asym_id_2           VARCHAR(10),
    auth_comp_id_2           VARCHAR(10),
    auth_seq_id_2            VARCHAR(20),
    PDB_ins_code_2           VARCHAR(5),
    label_alt_id_2           VARCHAR(5),
    auth_atom_id_3           VARCHAR(20),
    auth_asym_id_3           VARCHAR(10),
    auth_comp_id_3           VARCHAR(10),
    auth_seq_id_3            VARCHAR(20),
    PDB_ins_code_3           VARCHAR(5),
    label_alt_id_3           VARCHAR(5),
    angle_value              REAL,
    angle_target_value       REAL,
    angle_deviation          REAL,
    angle_standard_deviation REAL,
    linker_flag              VARCHAR(5),
    PRIMARY KEY (id),
    CONSTRAINT fk_vra_entry
        FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_vra_entry ON pdbx_validate_rmsd_angle (entry_id);
COMMENT ON TABLE pdbx_validate_rmsd_angle IS 'Angle RMSD outliers. entry_id injected by loader. CIF id ignored (IDENTITY).';
